site_name: ART-Framework
site_description: 'Home of the documentation for the ART-Framework.'
site_author: 'Michael Reichenbach'
docs_dir: docs/
repo_name: 'art-framework/art-framework'
repo_url: 'https://github.com/art-framework/art-framework'
nav:
  - Home: index.md
  - Developer: developer/index.md
  - Admins: admin/index.md
theme:
  name: 'material'