site_name: ART-Framework
site_description: 'Home of the documentation for the ART-Framework.'
site_author: 'Michael Reichenbach'
docs_dir: docs/
repo_url: 'https://github.com/art-framework/art-framework'
nav:
  - Home: index.md
  - 'Issue Tracker': 'https://github.com/art-framework/art-framework/issues'
  - 'About': 'about.md'
  - 'Server Admins':
    - 'Quickstart': 'admin/quickstart.md'
    - 'Installation': 'admin/installation.md'
    - 'Configuration':
      - 'General Syntax': 'admin/syntax/index.md'
      - 'Actions': 'admin/syntax/actions.md'
      - 'Requirements': 'admin/syntax/requirements.md'
      - 'Trigger': 'admin/syntax/trigger.md'
  - 'Developers':
    - 'Quickstart': 'developer/quickstart.md'
    - 'Creating ART':
      - 'Actions': 'developer/creating/actions.md'
      - 'Requirements': 'developer/creating/requirements.md'
      - 'Trigger': 'developer/creating/trigger.md'
      - 'Targets': 'developer/creating/target.md'
      - 'Filter': 'developer/creating/filter.md'
    - 'Handling Data': 'developer/creating/data.md'
    - 'Using ART': 'developer/use-art.md'
theme:
  name: 'readthedocs'
  titles_only: false
markdown_extensions:
  - smarty
  - admonition
  - codehilite
  - nl2br
  - sane_lists
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.superfences
  - pymdownx.details
plugins:
  - git-revision-date